### ISSUE TITLE
Please do not publish primitives_interfaces package

### ISSUE THREAD

**Issue by mitar** [neurodata/primitives-interfaces#3]
You are breaking all other packages in the JPL base image because you are overriding the official primitives_interfaces package.

See this line: https://github.com/neurodata/primitives-interfaces/blob/master/setup.py#L36

Please remove it.

Please do this ASAP because you are breaking all other primitives implementing primitives interfaces in the base image.

**Comment by mitar** [comment]
You probably want to remove primitives interfaces code from this repo and just use it from official repo, so that you can be sure it works with the package in the base image.

**Comment by disa-mhembere** [comment]
This repo was created as a publicly visible testbed since d3m is accessed controlled. Ideally it would  be a fork of the real d3m repo and submit pull requests when we wanted to merge, but that is not possible. I would suggest relaying this to Youngser or pointing him towards this issue since he will take over development in the future I believe -- I'm not part of the project and was just helping out.
