### ISSUE TITLE
ta2 pipeline examples (?)

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/primitives-interfaces#68]
talk to daragh & co

**Comment by alyakin314** [comment]
unfortunately due to the attributes issue (#66), all of the datasets that are both a) edgelist  and b) have node attributes will have a terrible perofrmance, because attributes cannot be incorporated into the embedding properly. 

thus, we have the following options as our pipelines to pitch to a TA2 team:
VC on the net_nomination_seed (obviously not the edgelist version) 
LP

**Comment by alyakin314** [comment]
we now also have seeded graph matching, though it's a little skech because it is a one-dataset pipeline and i would want to keep that fact under brians radar until we break it down into separate pieces and possibly also merge it with a graph reader.

**Comment by alyakin314** [comment]
ta2 team has made an lse-gclass pipeline from our primtives. 

closing.
